version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Pre-build started on `date`
      - mvn --version
  build:
    commands:
      - echo Build started on `date`
      - cd SourceCode
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - SourceCode/target/JavaWebApp.war
