version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/download_and_move_war.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/restart_tomcat.sh
      timeout: 60
      runas: root
